output_dir : "./output"

URL      : "http://localhost:8000"
app_port : 7860

llm_config:
  model_id    : "google/gemma-3-4b-it"
  language    : "korean"
  device      : "cuda"
  sys_prompt  : "You are a professional translator. Accurately translate the provided text and output only the result without any explanations in"
  user_prompt : "Translation this sentence"
  temperature : 0.3
  gpu_memory_utilization : 0.8
